import React from 'react';
import { useTheme } from '../../contexts/ThemeContext';

interface InsightEvidenceProps {
  evidence: {
    reasoning?: string;
    data_points?: string[];
    source_pointers?: string[];
    generated_by_agent?: string;
    semantic_entries_count?: number;
    file_changes_count?: number;
    comprehensive_summaries_count?: number;
    session_summaries_count?: number;
    most_active_files?: string[];
  };
  onClose?: () => void;
}

const InsightEvidence: React.FC<InsightEvidenceProps> = ({ evidence, onClose }) => {
  const { currentTheme } = useTheme();
  
  const isDark = currentTheme.name.toLowerCase().includes('dark');

  const formatDate = (timestamp: string) => {
    try {
      return new Date(timestamp).toLocaleString();
    } catch {
      return 'Invalid date';
    }
  };

  return (
    <div className={`${isDark ? 'text-white' : 'text-gray-900'}`}>
      
      {evidence.reasoning && (
        <div className="mb-3">
          <h4 className={`text-sm font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
            Why this matters
          </h4>
          <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>
            {evidence.reasoning}
          </p>
        </div>
      )}
      
      {evidence.data_points && evidence.data_points.length > 0 && (
        <div className="mb-3">
          <h4 className={`text-sm font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
            Data Points
          </h4>
          <ul className={`list-disc list-inside space-y-1 text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>
            {evidence.data_points.map((point, index) => (
              <li key={index} className="flex items-start">
                <span className={`inline-block max-w-xs truncate ${isDark ? 'bg-gray-700' : 'bg-gray-200'}
                           text-gray-800 dark:text-gray-200 px-2 py-1 rounded text-xs`}>
                  {point}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
      
      {evidence.source_pointers && evidence.source_pointers.length > 0 && (
        <div className="mb-3">
          <h4 className={`text-sm font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
            Source Pointers
          </h4>
          <ul className={`list-disc list-inside space-y-1 text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>
            {evidence.source_pointers.map((pointer, index) => (
              <li key={index} className="flex items-start">
                <span className={`inline-block max-w-xs truncate ${isDark ? 'bg-gray-700' : 'bg-gray-200'}
                           text-gray-800 dark:text-gray-200 px-2 py-1 rounded text-xs`}>
                  {pointer}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
      
      <div className="mt-4 pt-3 border-t border-gray-200 dark:border-gray-700">
        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-500 dark:text-gray-400">
            Generated by {evidence.generated_by_agent || 'AI'}
          </div>
          
          <div className="flex gap-4 text-xs text-gray-400">
            <span>Analysis Scope:</span>
            <span className="ml-2 font-medium text-gray-700 dark:text-gray-300">
              {evidence.semantic_entries_count || 0} semantic entries
            </span>
            <span className="ml-2 font-medium text-gray-700 dark:text-gray-300">
              {evidence.file_changes_count || 0} file changes
            </span>
            <span className="ml-2 font-medium text-gray-700 dark:text-gray-300">
              {evidence.comprehensive_summaries_count || 0} comprehensive summaries
            </span>
            <span className="ml-2 font-medium text-gray-700 dark:text-gray-300">
              {evidence.session_summaries_count || 0} session summaries
            </span>
          </div>
        </div>
        
        {evidence.most_active_files && evidence.most_active_files.length > 0 && (
          <div className="mt-3">
            <h4 className={`text-sm font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
              Most Active Files
            </h4>
            <div className="flex flex-wrap gap-2">
              {evidence.most_active_files.map((file, index) => (
                <span key={index} className={`inline-block max-w-xs truncate ${isDark ? 'bg-gray-700' : 'bg-gray-200'}
                             text-gray-800 dark:text-gray-200 px-2 py-1 rounded text-xs`}>
                  {file.split('/').pop()}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default InsightEvidence;